name: LOCASCIO-CLOUD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: /usr/local/bin/composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: /usr/local/bin/composer install --prefer-dist --no-progress --no-suggest
      
    - name: Setup MySql Credentials in config.php
      run: echo "<?php define('DOMAIN', '');" > config.php && echo "define('DB_HOST', '127.0.0.1'); " >> config.php && echo "define('DB_NAME', '${{ secrets.DATABASE_NAME }}');" >> config.php && echo "define('DB_USERNAME', '${{ secrets.DATABASE_USER }}');" >> config.php && echo "define('DB_PASSWORD', '${{ secrets.DATABASE_PASSWD }}');" >> config.php

#     Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
#     Docs: https://getcomposer.org/doc/articles/scripts.md

#     - name: Run test suite
#       run: composer run-script test
