name: LOCASCIO-CLOUD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: /usr/local/bin/composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: /usr/local/bin/composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    #PhpMyAdmin STEPS
    - name: Go to PhpMyadmin directory
      run: cd assets/phpMyAdmin
    - name: Validate composer.json and composer.lock to PhpMyAdmin Directory
      run: /usr/local/bin/composer validate --strict
    -name: Install dependencies to PhpMyAdmin Directory
      run: /usr/local/bin/composer install --prefer-dist --no-progress --no-suggest
